# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/535-nbdev-tutorial',
                'doc_host': 'https://RussellRyanH.github.io',
                'git_url': 'https://github.com/RussellRyanH/535-nbdev-tutorial',
                'lib_path': '535_nbdev_tutorial'},
  'syms': {'535_nbdev_tutorial.core': {'535_nbdev_tutorial.core.foo': ('core.html#foo', '535_nbdev_tutorial/core.py')}}}
